services:
  backend:
    image: algo_backend
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: ${DB_NAME}й
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: