site_name: Algo Notes
site_description: Документация проекта Algo Notes
site_author: Denisonya

repo_name: Denisonya/algo-notes
repo_url: https://github.com/Denisonya/algo-notes
edit_uri: edit/main/docs/

theme:
  name: material
  language: ru
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.select
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Переключить на тёмную тему
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Переключить на светлую тему
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Главная: index.md

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Denisonya/algo-notes
      name: GitHub repository
